name: Upgrade Mint Dependencies

on:
  repository_dispatch:
    types: [upgrade-mint-dependencies]

jobs:
  upgrade-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo Workflow executed!
